export const MEDICAL_CONDITIONS_DB = [
  {
    id: 'diabetes_t1',
    keywords: ['type 1 diabetes', 'insulin dependent', 'juvenile diabetes', 't1d'],
    severity: 'CRITICAL',
    rescuerAlert: '⚠️ PATIENT MAY NEED INSULIN — Check for medical kit or insulin pump',
    firstAid: [
      'If unconscious and diabetic: DO NOT give food/drink by mouth',
      'Look for insulin pump on body (arm/abdomen)',
      'Call emergency services immediately',
      'If patient is conscious and blood sugar is low: give 15g fast sugar (juice, glucose tablet)',
    ],
    warnSymptoms: ['unconscious', 'sweating', 'shaking', 'confusion'],
  },
  {
    id: 'diabetes_t2',
    keywords: ['type 2 diabetes', 'diabetes mellitus', 'diabetic', 'diabetes'],
    severity: 'HIGH',
    rescuerAlert: '⚠️ DIABETIC PATIENT — Monitor for hypoglycemia',
    firstAid: [
      'If conscious: ask if they have glucose tablets or candy',
      'Do not give food/drink if unconscious',
      'Place in recovery position if unconscious',
    ],
    warnSymptoms: ['dizziness', 'confusion', 'sweating'],
  },
  {
    id: 'epilepsy',
    keywords: ['epilepsy', 'epileptic', 'seizure disorder', 'fits', 'convulsions'],
    severity: 'CRITICAL',
    rescuerAlert: '🔴 SEIZURE RISK — Do NOT restrain. Time the seizure.',
    firstAid: [
      'Do NOT hold the person down or put anything in their mouth',
      'Clear area of hard/sharp objects',
      'Time the seizure — if over 5 minutes, call emergency',
      'After seizure: place in recovery position (on side)',
      'Stay with patient until fully conscious',
    ],
    warnSymptoms: ['shaking', 'jerking', 'stiff', 'unconscious'],
  },
  {
    id: 'heart_condition',
    keywords: ['heart disease', 'cardiac', 'heart attack', 'angina', 'arrhythmia', 'pacemaker', 'heart failure', 'coronary'],
    severity: 'CRITICAL',
    rescuerAlert: '🔴 CARDIAC PATIENT — Check for pacemaker before defibrillator use',
    firstAid: [
      'If chest pain: have patient sit/lie in comfortable position',
      'Loosen tight clothing',
      'If patient has prescribed nitroglycerine: assist with it',
      'Do NOT give aspirin without confirming no allergy',
      'If pacemaker: do NOT use AED paddles directly over it',
      'Be ready to perform CPR if patient stops breathing',
    ],
    warnSymptoms: ['chest pain', 'shortness of breath', 'unconscious', 'pale'],
  },
  {
    id: 'asthma',
    keywords: ['asthma', 'asthmatic', 'inhaler', 'bronchial asthma', 'respiratory'],
    severity: 'HIGH',
    rescuerAlert: '⚠️ ASTHMA — Check for inhaler in patient\'s bag/pocket',
    firstAid: [
      'Help patient sit upright — leaning slightly forward',
      'Look for blue/silver inhaler in patient\'s belongings',
      'If using inhaler: shake well, 1 puff every 30-60 seconds (max 10 puffs)',
      'Loosen tight clothing around neck',
      'Keep patient calm — anxiety worsens asthma',
      'If no improvement in 15 minutes: call emergency immediately',
    ],
    warnSymptoms: ['wheezing', 'difficulty breathing', 'blue lips'],
  },
  {
    id: 'blood_thinner',
    keywords: ['blood thinner', 'warfarin', 'aspirin', 'anticoagulant', 'heparin', 'eliquis', 'xarelto', 'clopidogrel'],
    severity: 'HIGH',
    rescuerAlert: '⚠️ ON BLOOD THINNERS — Even minor bleeding can be dangerous. Apply firm pressure.',
    firstAid: [
      'Apply FIRM direct pressure to any bleeding wound',
      'Do NOT remove cloth used to apply pressure — add more on top',
      'Blood thinners mean normal clotting WON\'T occur',
      'Any significant bleeding needs immediate hospital attention',
      'Inform doctors about blood thinner medication',
    ],
    warnSymptoms: ['bleeding', 'bruising'],
  },
  {
    id: 'allergy_penicillin',
    keywords: ['penicillin allergy', 'amoxicillin allergy', 'antibiotic allergy'],
    severity: 'CRITICAL',
    rescuerAlert: '🚨 PENICILLIN ALLERGY — Alert hospital before any antibiotic administration',
    firstAid: [
      'CRITICAL: Inform paramedics and hospital staff immediately',
      'Do NOT administer penicillin or amoxicillin',
      'Inform of allergy before any IV antibiotic is given',
    ],
    warnSymptoms: [],
  },
  {
    id: 'anaphylaxis',
    keywords: ['anaphylaxis', 'anaphylactic', 'epipen', 'epinephrine', 'severe allergy', 'adrenaline auto-injector'],
    severity: 'CRITICAL',
    rescuerAlert: '🚨 ANAPHYLAXIS RISK — Look for EpiPen immediately. Use if patient is in shock.',
    firstAid: [
      'Look for EpiPen/auto-injector in patient\'s bag or pocket',
      'If anaphylaxis: inject EpiPen into outer thigh (through clothing is OK)',
      'Call emergency services IMMEDIATELY after EpiPen use',
      'Lay patient flat with legs elevated (unless breathing difficulty)',
      'A second EpiPen may be needed after 5-15 minutes if no improvement',
    ],
    warnSymptoms: ['rash', 'swelling', 'difficulty breathing', 'pale', 'unconscious'],
  },
  {
    id: 'hypertension',
    keywords: ['hypertension', 'high blood pressure', 'bp medication', 'antihypertensive'],
    severity: 'MEDIUM',
    rescuerAlert: 'ℹ️ HYPERTENSIVE PATIENT — Keep calm. Avoid stimulants.',
    firstAid: [
      'Keep patient calm and seated',
      'Avoid giving caffeine or stimulants',
      'If patient has prescribed medication and is conscious: assist them',
    ],
    warnSymptoms: ['severe headache', 'confusion', 'nosebleed'],
  },
  {
    id: 'kidney_disease',
    keywords: ['kidney disease', 'renal failure', 'dialysis', 'kidney failure', 'chronic kidney'],
    severity: 'HIGH',
    rescuerAlert: '⚠️ KIDNEY DISEASE — Avoid NSAIDs (ibuprofen). Inform hospital for IV fluid decisions.',
    firstAid: [
      'Do NOT give ibuprofen, naproxen, or other NSAIDs for pain',
      'Inform hospital/paramedics of kidney condition immediately',
      'Note dialysis schedule if available',
    ],
    warnSymptoms: [],
  },
  {
    id: 'thyroid',
    keywords: ['thyroid', 'hypothyroid', 'hyperthyroid', 'thyroxine', 'levothyroxine', 'graves disease'],
    severity: 'LOW',
    rescuerAlert: 'ℹ️ THYROID CONDITION — Inform hospital for medication continuity',
    firstAid: [
      'Inform hospital of thyroid condition',
      'If patient takes thyroid medication daily, note this for medical staff',
    ],
    warnSymptoms: [],
  },
  {
    id: 'pregnancy',
    keywords: ['pregnant', 'pregnancy', 'expecting', 'trimester'],
    severity: 'HIGH',
    rescuerAlert: '⚠️ PATIENT MAY BE PREGNANT — Avoid certain medications. Position on left side.',
    firstAid: [
      'If unconscious: position on LEFT side to avoid compressing vena cava',
      'Avoid X-rays unless life-threatening emergency',
      'Do NOT give aspirin, ibuprofen, or most pain medications',
      'Inform hospital of pregnancy status immediately',
    ],
    warnSymptoms: [],
  },
  {
    id: 'mental_health',
    keywords: ['schizophrenia', 'bipolar', 'psychosis', 'psychiatric', 'antipsychotic'],
    severity: 'MEDIUM',
    rescuerAlert: 'ℹ️ PSYCHIATRIC CONDITION — Approach calmly. Avoid restraint if possible.',
    firstAid: [
      'Speak calmly and clearly',
      'Do not make sudden movements',
      'Inform paramedics of psychiatric history',
      'If on antipsychotic medication: note for hospital',
    ],
    warnSymptoms: [],
  },
  {
    id: 'hemophilia',
    keywords: ['hemophilia', 'haemophilia', 'clotting disorder', 'bleeding disorder', 'von willebrand'],
    severity: 'CRITICAL',
    rescuerAlert: '🚨 BLEEDING DISORDER — Patient cannot clot normally. Any bleeding is an emergency.',
    firstAid: [
      'Apply CONSTANT firm direct pressure to ALL wounds',
      'Do NOT remove dressing — add more on top',
      'Even small cuts require hospital treatment',
      'Inform hospital immediately — patient may need clotting factor',
      'Avoid IM injections if possible',
    ],
    warnSymptoms: ['bleeding', 'bruising', 'swelling in joints'],
  },
  {
    id: 'hiv',
    keywords: ['hiv', 'aids', 'antiretroviral', 'art therapy'],
    severity: 'MEDIUM',
    rescuerAlert: 'ℹ️ HIV STATUS — Standard universal precautions. Inform hospital for medication continuity.',
    firstAid: [
      'Use standard universal precautions (gloves)',
      'Inform hospital of HIV status for medication continuity',
      'Patient may be on antiretroviral therapy — do not skip doses',
    ],
    warnSymptoms: [],
  },
];

export type SeverityLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE';
